### PR TITLE
First draft of swedish translation

### PR DESCRIPTION
**Pull request by mp-se**
Translation into swedish

### CODE REVIEW

**Comment by lbussy** [comment]
That one "translation" about how ugly his dog is, is hilarious!  😀

**Comment by thorrak** [comment]
Thank you so much for this - I'll get this merged immediately!

If you have a moment and wouldn't mind, would you mind taking a stab at translating the following text from the ["manual flash mode" page](http://www.brewflasher.com/manualflash/)? 



# Manually toggling "Flash" Mode

For certain chips (e.g. ESP32-S2) the USB-to-serial functionality is provided by the controller itself rather than a separate piece of hardware. For these chips, you may be required to manually set the controller into "flash" mode before BrewFlasher can install new firmware. Below is the process for doing this for the Lolin S2 mini -- other controllers are likely similar (though the "0" button may be labeled something else, like "boot" or "flash")

1.	Plug the Lolin S2 Mini into your computer
2.	Hold down the "0" button on the right of the board
3.	While continuing to hold the "0" button, press the "RST" button on the left of the board
4.	Wait several seconds, then release the "0" button
5.	Flash your controller with the desired firmware
6.	Manually press the "RST" button on the left of the board to reset the controller once flashing is complete

**Comment by thorrak** [comment]
Also, is 

"För instruktioner om hur man gör detta, kontrollera denna webbplats: http://www.brewflasher.com/manualflash/" 

a good translation for 

"For instructions on how to do this, check this website: http://www.brewflasher.com/manualflash/" ?

**Comment by mp-se** [comment]
Sure here is the translation:

Manuellt starta “programmeringsläge”
För vissa enheter (tex ESP32-S2) så hanteras den seriella porten av processorn utan stöd av separat hårdvara. Det kan hända att man manuellt måste tvinga in dessa enheter i ”programmeringsläge” innan Brewflasher kan installera mjukvaran. Här visas de steg som krävs för en Lolin S2 Mini – andra enheter har en liknande process men knappen kan han ett annat namn, tex BOOT, FLASH. 
1.	Koppla in Lolin S2 Mini till datorn
2.	Håll ner ”0” knappen på höger sida av enheten.
3.	Samtidigt som knappen hålls ner så tryck på ”RST” knappen på vänster sida av enheten.
4.	Vänta några sekunder och släpp sedan ”0” knappen
5.	Programmera enheten med ditt val av mjukvara
6.	Tryck på ”RST” knappen på vänster sida av enheten när programmeringen är klar och enheten går ur ”programmeinrgsläget”.

**Comment by thorrak** [comment]
Thank you so much - The instructions are now [updated](http://www.brewflasher.com/manualflash/)!

I'm traveling at the moment, but I'll try to get a release of BrewFlasher out with this update here in the next few days. Thanks again for this - I really appreciate it!

**Comment by mp-se** [comment]
> 

Its a good translation

**Comment by mp-se** [comment]
No problems, happy to assist

**Pull request merged**
